### ISSUE TITLE
Suggestion: Sound adjustment slider.

### ISSUE THREAD

**Issue by SirAron111** [MrVauxs/dnd5e-animations#14]
Hi, I would like to suggest that a Sound adjustment slider would be a nice touch to the module. I like the sounds, but they are extremely loud once they play on the same sound source as other effects or ambiance sound, players can't just turn them down, or they won't be able to hear the bgm.

So a universal setting that lets you adjust all sounds with a slider from this module would be nice.
Even if the sound would be reduced to 0,15 from the 0,75 it's at would be good as they are real loud by default which isn't good for an immersive game experience.

**Comment by MrVauxs** [comment]
You can already adjust the sounds in the Playlist tab, Interface volume.
![image](https://github.com/MrVauxs/dnd5e-animations/assets/32039708/79e75a0a-b6de-4589-ae17-3a5c472f2f31)

**Comment by SirAron111** [comment]
Ye, but that also reduces all the sound for dice rolling or other things. What I meant was one specifically for the effects because I had to manually set them all down to 0,25 percent from the initial 0,75 in each individual animation automation setting, because it was simply too loud.

**Comment by SirAron111** [comment]
@MrVauxs Or at least have an option in the update interface, that asks you if you want all sounds to be updated to lower or higher volumes. Like 1 / 0.75 / 0.5 /0.25 and 0 percent for the module. So it doesn't blast everyone's ears out.

**Comment by MrVauxs** [comment]
Best considered along with #8
