### ISSUE TITLE
New sound for firing bows

### ISSUE THREAD

**Issue by Krigsmaskine** [MrVauxs/dnd5e-animations#15]
Hi,

As a Dota 2 player, I got instant ptsd from hearing Techies attacking from a bow (slight hyperbole 😃), could they perhaps be changed to one of the bow using heroes' instead? AA/Sequencer allows wildcards, so you could use all of Mirana's attack sounds for instance for variation and they sound more bow-y. 

https://dota2.fandom.com/wiki/Mirana/Sounds
Projectile launch 1-4

edit: found out the hotlinks I made didn't seem to work, linking to the page where they are instead

**Comment by MrVauxs** [comment]
As much as I'd love to use Dota 2 sounds (played 1k hours), I am not sure
if I'm allowed to legally.

wt., 4 lip 2023, 13:06 użytkownik Krigsmaskine ***@***.***>
napisał:

**Comment by Krigsmaskine** [comment]
You already use them (the sound in modules\dnd5e-animations\assets\sounds\Weapons\Ranged_Projectile\ranged-projectile-launch.mp3 is the Techies attack sound here https://static.wikia.nocookie.net/dota2_gamepedia/images/5/55/Techies_projectile_launch.mp3/revision/latest?cb=20141210140723) and credit them in the module 😄 Seems like they're lifted from the same wiki I linked with the license included?
![image](https://github.com/MrVauxs/dnd5e-animations/assets/39592771/221274a0-65b9-4bb8-9408-17f778ab88f9)

**Comment by MrVauxs** [comment]
Yeah I noticed after writing the email response, thought this issue was in the PF2e Animations repo.
@Sisimshow manages all that.

**Comment by Sisimshow** [comment]
I've heard other people comment on the sound effects used for the bows, so I changed them in the last update. Could you please update to 1.5.0 and let me know what you think?
