### ISSUE TITLE
Changelog points to `main` branch

### ISSUE THREAD

**Issue by rikmarais** [MrVauxs/dnd5e-animations#16]
https://github.com/MrVauxs/dnd5e-animations/releases/download/1.5.0/module.json

![image](https://github.com/MrVauxs/dnd5e-animations/assets/34374883/e0be5845-ac54-4121-bc5d-ab9bec52ad32)

![image](https://github.com/MrVauxs/dnd5e-animations/assets/34374883/35847025-25aa-4dad-8e30-2f97392bf027)

I think it should point to `master` branch, not `main` :)

**Comment by MrVauxs** [comment]
Resolved in next update.
