### ISSUE TITLE
Fix 3D Levels Asset Paths

### ISSUE THREAD

**Issue by oeey** [MrVauxs/dnd5e-animations#18]
Yet another premium dependency?  The description of dnd5e-animations states that only JB2A and Automated Animations are required, but there are 844 referenced "modules/levels-3d-preview" in the autorec.json, where there are only 649 JB2A references.  Should replace with assets built into the dnd5e-animations asset folder (or JB2A).

---

Eveni f you decide to keep the levels-3d-preview references you should fix the following references:

dust.webp was renamed to dust.png in levels-3d-preview: (correct in most places, but several still exist)
* "sprite": "modules/levels-3d-preview/assets/particles/dust.webp"

emberssmall.webp was renamed to emberssmall.png in levels-3d-preview: (correct in most places, but several still exist)
* "sprite": "modules/levels-3d-preview/assets/particles/emberssmall.webp"

Extra space at end of filename:
* "spritePath": "modules/levels-3d-preview/assets/particles/magiccircles/magic_circle_09.webp "
* "spritePath": "modules/levels-3d-preview/assets/particles/magiccircles/magic_circle_11.webp "
* "spritePath": "modules/levels-3d-preview/assets/particles/magiccircles/magic_circle_12.webp "

**Comment by MrVauxs** [comment]
It's not a dependency. The integration with levels 3d is optional and purely for those who actually use it, made by an outside collaborator.
If you don't have it, you don't have to worry about it at all. It doesn't show up.

Will fix the typos.
