### ISSUE TITLE
Feature Request - Add Animation for Status Effects

### ISSUE THREAD

**Issue by Zandelar** [MrVauxs/dnd5e-animations#21]
It would be super cool if you could put JB2A animations on token to represent different status effects such as Prone, Restrained etc.

**Comment by MrVauxs** [comment]
Unlikely to happen, as it was already a thing and has been removed due to excessive animations whenever anyone had more than 1 condition (like because they are Dying), and the fact that it killed performance for some.

**Comment by Zandelar** [comment]
Understood. I didn't think about it that way. Thanks for the reply.
