### ISSUE TITLE
"Cannot be enabled due to issues in required dependencies"

### ISSUE THREAD

**Issue by WZerbato** [MrVauxs/dnd5e-animations#23]
Hello there,

I am hosting my World in a TheForge server. 

I recently updated to Foundry V12 and when trying to enable DnD5e Animations, I could not due to this error : "Cannot be enabled due to issues in required dependencies"

Is this issue known ? Is this from the V12 update ?

Thank you in advance !

**Comment by MrVauxs** [comment]
You need to have Automated Animations installed, which is not yet V12 compatible.
