### ISSUE TITLE
[BUG] Deprecation warning for global function call in FoundryVTT v12

### ISSUE THREAD

**Issue by morepurplemorebetter** [MrVauxs/dnd5e-animations#29]
## Description
I'm getting a warning message in my console from this module:
```
Error: You are accessing globalThis.isNewerVersion which must now be accessed via foundry.utils.isNewerVersion
Deprecated since Version 12
Backwards-compatible support will be removed in Version 14
[...]
wrongVersions https://[address]/modules/dnd5e-animations/module/utils.js:27
[...]
```

As far as I can tell, accessing these through `foundry.utils` is also supported in FoundryVTT v10 & v11. Thus, changing this won't affect the other versions this module works with.

## Versions
D&D5e Animations: v1.7.1
FoundryVTT: v12.331

**Comment by MrVauxs** [comment]
Fixed in the next version.
