### ISSUE TITLE
Suggestion: synchronising sounds with animations

### ISSUE THREAD

**Issue by rpganalyst** [MrVauxs/dnd5e-animations#3]
Hello, thank you for your work with this module.
To be honest, I do not know neither if the delay between animations and sounds is fixable at your end, neither if it's a simple fix.
I fixed manually the animations I needed in game. This was the only way I found to synchronize them with sounds that plays in advance.

Thank you.

**Comment by MrVauxs** [comment]
Released in [1.1.0](https://github.com/MrVauxs/dnd5e-animations/releases/tag/1.1.0)
