### ISSUE TITLE
D&D5e Animations doesn't work for me anymore.

### ISSUE THREAD

**Issue by DarthBalrog** [MrVauxs/dnd5e-animations#30]
Hi,
First of all I loved your module!

But now... D&D5e Animations doesn't work for me anymore.
Anyone have any suggestions?

D&D5e Animations version: 1.7.1
Foundry version: 11 Build 315.

Thank you!
-DB

**Comment by DarthBalrog** [comment]
Thanks for the quick reply!

Automated Animations version: 4.2.81
Game System: D&D Fith Edition 3.3.1

Do you suggest me to upgrade Foundry to v12?

**Comment by MrVauxs** [comment]
Downgrade A-A to 4.2.80 or upgrade your Foundry to v12 and D&D to V4. This
choice is entirely up to you.

czw., 17 paź 2024, 15:54 użytkownik DarthBalrog ***@***.***>
napisał:

**Comment by DarthBalrog** [comment]
Ok.
I'll think about it and then I'll decide.
Maybe it's time to upgrade to foundry version 12.
Although it scares me a bit. I fear I may have problems with other things...

In the meantime, thanks!
