### ISSUE TITLE
[Issue] Sound not found arrow.

### ISSUE THREAD

**Issue by rpganalyst** [MrVauxs/dnd5e-animations#4]
Hello I got this bug.
![image](https://user-images.githubusercontent.com/47994415/224652421-6309e528-f29c-47b8-bde3-a523807447f4.png)

Core: 10.191
System: dnd5e 2.1.5
dnd5e-animation: 1.1.1

**Comment by MrVauxs** [comment]
Fixed in [1.1.2](https://github.com/MrVauxs/dnd5e-animations/releases/tag/1.1.2)
