### ISSUE TITLE
Issues with status conditions

### ISSUE THREAD

**Issue by MotoMoto1234** [MrVauxs/dnd5e-animations#7]
This module comes up as the culprit every time.  

I have midiqol installed and when a monster dies, the dead condition or unconscious conditions are auto applied but are immediately toggled off.  I can only have this behavior stop if I disable this module.  Midi/dfreds CE are the usual modules that handle this behavior fine, but your module seems to be interfering with them.

**Comment by MrVauxs** [comment]
The module does not do anything with conditions, it doesn't even interact with the 5e system.
If anything, it is Automated Animations, or the modules themselves.
