### ISSUE TITLE
Feature Request: Adjust Sounds

### ISSUE THREAD

**Issue by hoyer1066** [MrVauxs/dnd5e-animations#8]
While the sounds are nice to have, they are very much a secondary part of the animations and I think less likely to be universally wanted. (Either due to the sounds not linking well with the animation timings, the sounds themselves not matching with what the users would choose, or the volume used in the animations being out of balance with everything else).

At the moment if someone wants to turn them off they need to A) turn off all sounds on Sequencer (which impacts everything using it), B) manually turn it off on every imported animation (which is very time intensive *and* means that they can't ever update the animations when the mod updates, or they'll have to do it all over again), or C) not use this mod at all.

Adding an ability to turn off the sounds before animations are imported would increase the accessibility of this mod to a lot more people

**Comment by hoyer1066** [comment]
I would just like to make it clear that I absolutely love this mod and what it makes possible, add this is very much a personal preference on things and a thought on how the mod could be more generally useful to a broader field of foundry users

**Comment by Sithishade** [comment]
I would like to echo support for this--I did not realize I could turn everything off in Sequencer, which I've just done to make this simpler, as I don't use Sequencer for anything else. Thanks for letting me know!

**Comment by roguedevjake** [comment]
seconding this, one of my players deafened themselves last session... Thankfully for me muting my interface volume as one of the first things I do when prepping foundry :)

**Comment by Sisimshow** [comment]
I feel I should comment on this. Because of the way sound effects are handled by Automated Animations and Sequencer, there is no simple way to lower the volume for just the D&D5e Animation effects without having a separate autorec file. I feel you all about wanting a separate slider though, I actually play with the sound effects muted myself. The sounds were mostly handled by others except for the newest additions but I wanted to include them since so many people like them. My suggestion is to mute Sequencer sound effects which is an option in the module's settings.

**Comment by Sisimshow** [comment]
I will close this as a not planned feature.

**Comment by Sisimshow** [comment]
.

**Comment by MrVauxs** [comment]
I got an idea how to implement this. Stay tuned.

**Comment by mkevans80** [comment]
Just wanted to voice my support for some way to adjust/mute sounds on a global level.  They are all so much louder than all the other sound stuff I run in my game, even stuff I have set at the highest possible volume.  Several times I have seen my players rip their headphones off their heads when an unexpected prolonged sound effect blows out their eardrums.  Now whenever I create a new item the first thing I do is go into the tab and reduce the sound effect to 0.25 or even lower.

All that being said, if just that one thing is addressed, this will become the absolute perfect mod!
